### ISSUE TITLE
Line break

### ISSUE THREAD

**Issue by risualiser** [darkreader/darkreader.org#1]
What about a common dividing line by two, when width of screen become small?
There is example of current view of site on my phone.
![screenshot](https://user-images.githubusercontent.com/35914376/36944201-63ca1c72-1fa8-11e8-8360-5ff5b516a9f0.png)

**Comment by risualiser** [comment]
I think I can close it now.

![](https://i.imgur.com/qQsyXPT.jpg)

**Comment by alexanderby** [comment]
I've added a fix for 320px screens, thanks.
