### ISSUE TITLE
Allow users to import/export settings via UI

### ISSUE THREAD

**Issue by sooper8** [darkreader/darkreader.org#14]
Please create import/export settings UI functionality so that you can maintain settings from a full re installation of browser and extension. JSON, TXT, or similar save format for simplicity

**Comment by DroneBetter** [comment]
You probably meant to use https://github.com/darkreader/darkreader.

This repo is for the website, darkreader.org.

**Comment by alexanderby** [comment]
This feature is available in new UI: click "Dev Tools", click "Preview new design", click "Settings", "Manage settings", see Import and Export there.

**Comment by sooper8** [comment]
Fantastic
Looks to be working as intended
