### ISSUE TITLE
Mobile Responsive UI

### ISSUE THREAD

**Issue by Yashank18** [darkreader/darkreader.org#19]
One of my friends told me about Darkreader the other day. 
I was on my phone and I went for darkreader.org but I found the website wasn't actually that appealing as the product is. So when I saw it on My PC, I found the dark reader a very cool and useful extension.
## Screenshots -

<img src="https://user-images.githubusercontent.com/46098062/81260813-67219f80-9058-11ea-8588-de381cd70091.png">
<img src="https://user-images.githubusercontent.com/46098062/81260745-3f323c00-9058-11ea-8004-2725dd4cd869.png">

## Proposed Changes 

* Margin for the Heading
* Center Align the platforms options
* Margin for the Screenshot

**Comment by alexanderby** [comment]
The start page was redesigned recently.
