### ISSUE TITLE
Is Google Analytics necessary?

### ISSUE THREAD

**Issue by gracjankn** [darkreader/darkreader.org#28]
The privacy policy states no data is ever collected (except for payment processing done by 3rd parties), however [Blacklight](Blacklight "https://themarkup.org/blacklight?url=darkreader.org") detected Google Analytics on this site.

Why is Google Analytics used here and is it really needed?

Google Analytics is one of the major contributors to widespread surveillance on the internet because it’s present on a significant percentage of websites and apps. [Even FOSS which should lead by example is unfortunately no exception.](https://reverseeagle.org/about/ "Even FOSS which should lead by example is unfortunately no exception.")
Preferably we could get rid of analytics all together, but if you absolutely need to collect some basic data [here’s a list of FOSS and privacy-friendly options.](https://developers.reverseeagle.org/replace/google-analytics/ "here’s a list of FOSS and privacy-friendly options.")

**Comment by alexanderby** [comment]
I don't know what is Blacklight, but it might be wrong. There's no Google Analytics on the website.

**Comment by gracjankn** [comment]
This is Interesting. Are there any other Google components on the site (Like Adsense, fonts, captchas, Youtube embeds etc)?

**Comment by alexanderby** [comment]
Yes, there are YouTube embeds, like here https://darkreader.org/blog/500k-users/
